apiVersion: v1
kind: Pod
metadata:
  name: neureka-api
  labels:
    app: neureka-api
    component: neureka-api
spec:
  containers:
    - image: neurekaacr.azurecr.io/neureka-api:v1
      name: neureka-api
      ports:
        - containerPort: 80