apiVersion: v1
kind: Service
metadata:
  labels:
    app: neureka-api
  name: neureka-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: neureka-api
    component: neureka-api