apiVersion: v1
kind: Service
metadata:
  labels:
    app: neureka-ui
  name: neureka-ui
  namespace: neureka-ui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 3100
  selector:
    app: neureka-ui